// Code generated by MockGen. DO NOT EDIT.
// Source: ./actions.go

// Package mock_actions is a generated GoMock package.
package mock_actions

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	"github.com/acceldata-io/wizard/internal/parser"
)

// MockAction is a mock of Action interface.
type MockAction struct {
	ctrl     *gomock.Controller
	recorder *MockActionMockRecorder
}

// MockActionMockRecorder is the mock recorder for MockAction.
type MockActionMockRecorder struct {
	mock *MockAction
}

// NewMockAction creates a new mock instance.
func NewMockAction(ctrl *gomock.Controller) *MockAction {
	mock := &MockAction{ctrl: ctrl}
	mock.recorder = &MockActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAction) EXPECT() *MockActionMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockAction) Do(actions *parser.Action, wizardLog chan interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", actions, wizardLog)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockActionMockRecorder) Do(actions, wizardLog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockAction)(nil).Do), actions, wizardLog)
}
